import { NextRequest, NextResponse } from "next/server";
import bcrypt from "bcryptjs";
import { COOKIE_NAME, MAX_AGE_SECONDS, createSessionToken } from "@/lib/session";

// This route intentionally supports exactly one account. There is no
// signup flow anywhere in this app. The password hash is supplied by
// the site owner via the ADMIN_PASSWORD_HASH environment variable
// (a bcrypt hash) — it is never chosen or generated by this codebase.
export async function POST(request: NextRequest) {
  const form = await request.formData();
  const password = String(form.get("password") ?? "");
  const from = String(form.get("from") ?? "/");

  const passwordHash = process.env.ADMIN_PASSWORD_HASH;

  if (!passwordHash) {
    return NextResponse.json(
      {
        error:
          "Server is not configured. ADMIN_PASSWORD_HASH environment variable is missing.",
      },
      { status: 500 }
    );
  }

  const isValid =
    password.length > 0 && (await bcrypt.compare(password, passwordHash));

  if (!isValid) {
    const url = new URL("/login", request.url);
    url.searchParams.set("error", "1");
    if (from.startsWith("/")) {
      url.searchParams.set("from", from);
    }
    return NextResponse.redirect(url, { status: 303 });
  }

  const redirectTarget = from.startsWith("/") ? from : "/";
  const url = new URL(redirectTarget, request.url);
  const response = NextResponse.redirect(url, { status: 303 });

  const token = await createSessionToken();
  response.cookies.set(COOKIE_NAME, token, {
    httpOnly: true,
    secure: true,
    sameSite: "lax",
    maxAge: MAX_AGE_SECONDS,
    path: "/",
  });

  return response;
}
