import { NextRequest, NextResponse } from "next/server";
import bcrypt from "bcryptjs";
import { COOKIE_NAME, MAX_AGE_SECONDS, createSessionToken } from "@/lib/session";

// This route intentionally supports exactly one account. There is no
// signup flow anywhere in this app. The password hash is supplied by
// the site owner via the ADMIN_PASSWORD_HASH environment variable
// (a bcrypt hash) — it is never chosen or generated by this codebase.
// (redeploy retry after Railway platform incident)

// Railway (and most reverse proxies) forward requests to this container
// using an internal address such as localhost:8080. request.url reflects
// that internal host, not the public domain, so we must prefer the
// X-Forwarded-Host / X-Forwarded-Proto headers when building absolute
// redirect URLs, or users get redirected to a broken internal address.
function getPublicOrigin(request: NextRequest): string {
    const forwardedHost = request.headers.get("x-forwarded-host");
    const forwardedProto = request.headers.get("x-forwarded-proto") ?? "https";
    const host = forwardedHost ?? request.headers.get("host");
    if (host) {
          return `${forwardedProto}://${host}`;
    }
    return new URL(request.url).origin;
}

export async function POST(request: NextRequest) {
    const form = await request.formData();
    const password = String(form.get("password") ?? "");
    const from = String(form.get("from") ?? "/");
    const passwordHash = process.env.ADMIN_PASSWORD_HASH;
    const origin = getPublicOrigin(request);

  if (!passwordHash) {
        return NextResponse.json(
          { error: "Server is not configured. ADMIN_PASSWORD_HASH environment variable is missing." },
          { status: 500 }
              );
  }

  const isValid = password.length > 0 && (await bcrypt.compare(password, passwordHash));

  if (!isValid) {
        const url = new URL("/login", origin);
        url.searchParams.set("error", "1");
        if (from.startsWith("/")) {
                url.searchParams.set("from", from);
        }
        return NextResponse.redirect(url, { status: 303 });
  }

  const redirectTarget = from.startsWith("/") ? from : "/";
    const url = new URL(redirectTarget, origin);
    const response = NextResponse.redirect(url, { status: 303 });
    const token = await createSessionToken();
    response.cookies.set(COOKIE_NAME, token, {
          httpOnly: true,
          secure: true,
          sameSite: "lax",
          maxAge: MAX_AGE_SECONDS,
          path: "/",
    });
    return response;
}
